global using Basket.API.Models;
global using BuildingBlocs.CQRS;
global using Carter;
global using Basket.API.Data;
global using Mapster;
global using MediatR;
global using FluentValidation;
global using BuildingBlocs.Exceptions;
global using Marten;