global using BuildingBlocs.CQRS;
global using Carter;
global using Catalog.API.Models;
global using Mapster;
global using Marten;
global using MediatR;
global using FluentValidation;
global using BuildingBlocs.Behaviors;
global using BuildingBlocs.Exceptions.Handlers;
